# Test your FastAPI endpoints

POST http://127.0.0.1:8000/api/SetUIN
Content-Type: application/json
Accept: application/json

{
  "UINs": ["6432500524257096","6432500538951151"],
  "login": "admin",
  "password": "h6mCbIA0GN"
}

###

POST http://127.0.0.1:8000/api/DeleteUIN
Content-Type: application/json
Accept: application/json

{
  "UINs": ["6432500524257096"],
  "login": "admin",
  "password": "h6mCbIA0GN"
}

###

GET http://127.0.0.1:8000/api/GetUINStatus
Accept: application/json

###
